### ISSUE TITLE
FeedbackInfo

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-familysearch-extensions#1]
[FeedbackInfo](https://familysearch.org/developers/docs/api/types/json_FeedbackInfo) is being used in the places API. It appears on the [FamilySearchPlatform](https://github.com/FamilySearch/gedcomx-familysearch-extensions/blob/master/specifications/gedcomx-familysearch-specification.md#fsp-json) data type as an array at the property `feedbackInfo`.

**Comment by justincy** [comment]
@stoicflame The documentation you added says

> Instances of `FeedbackInfo` can be reasonably expected as extension elements to the [`PlaceDescription` Data Type](https://github.com/FamilySearch/gedcomx/blob/master/specifications/conceptual-model-specification.md#place-description).

Is that correct? The [examples](https://familysearch.org/developers/docs/api/places/Read_Place_Feedback_usecase) in the developer docs have it as an extension to the Gedcomx/FamilySearchPlatform data type. It also wouldn't need the `place` property it if was already in the PlaceDescription.

**Comment by stoicflame** [comment]
The spec is correct; the example was incorrect and has been fixed.

Feedback is provided by submitting a description of a place. The `FeedbackInfo` was created to provide some extra information about the place that was submitted for feedback.

Example:

Someone submits a description of a cemetery as feedback. We'll call that description that was submitted "PD-1". A subsequent `GET` of that feedback will return "PD-1", which may have a pointer to a different place (we'll call it "PD-2") that was created as a result of the feedback.
